name: Run E2E Tests Cypress

on:
  push:
    branches:
      - master
    paths:
      - 'discuss/cypress/**.js'
      - 'discuss/cypress/**.json'
      - 'discuss/cypress/**.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'discuss/cypress/**.js'
      - 'discuss/cypress/**.json'
      - 'discuss/cypress/**.yml'

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: 'npm'

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Install dependencies
        run: npm ci
        working-directory: ./discuss

      - name: Run Cypress tests
        run: npm run cypress:headless -- --config baseUrl=http://localhost:3000
        working-directory: ./discuss
