name: Run E2E Tests Cypress

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'cypress/**'
      - '.github/workflows/cypress-e2e-tests.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'cypress/**'
      - '.github/workflows/cypress-e2e-tests.yml'

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: discuss
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d discuss"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
          command: npm run cypress:build
        env:
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_TRUST_HOST: true
          AUTH_URL: http://localhost:3000
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/discuss?schema=public
          DIRECT_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/discuss?schema=public
